# appveyor.yml
version: 1.0.{build}

image: Ubuntu

# 환경 변수 선언 (Linux에서는 $nodejs_version 으로 사용)
environment:
  nodejs_version: "18.20.2"

# 설치 스크립트
install:
  # nvm 설치
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  # node 설치
  - nvm install $nodejs_version
  - nvm use $nodejs_version
  - node -v
  - npm -v
  # 패키지 설치
  - npm ci

# 빌드 단계
build_script:
  - npm run build

# 테스트 단계
test_script:
  - npm run check
